### ISSUE TITLE
Setting time down counter?

### ISSUE THREAD

**Issue by pedroriverove** [aneeshikmat/yii2-time-down-counter#6]
First of all, thanks for the contribution, I want to know if this extension would work for me, I have orders that are saved with a time stamp data type, this request is addressed to an establishment that has a minimum delivery time (which must be fulfilled )), and I need to build a timer based on these two parameters.

For example:

If an order is created on 3 Jul. 2018 10:09:03 and the establishment must deliver it in less than 20 minutes, a stopwatch should appear running those 20 minutes and until July 3. 2018 10:29:03 it should expire.

Thank you very much.

**Comment by aneeshikmat** [comment]
Hi Pedro, 

First of All I would like to say thank you for interesting and ask this question.

About your question,  And If I got understand your case truth, I will say yes, you can :D, 
You have an option in this widget to determine time, finish message or callback code for complex or custom cases like this.

But keep note, this widget work as a client side, so that any action may be work with server side you can post it by ajax call in callback function ^_*.

Also about using two dates as param, this cant be now, you need to calculate a diff between times then assign it to widget. Also I think its a nice feature to be added to this widget in near future :D

Many Thanks.
